export const colors = {
  primary: '#00e0ff',
  backgroundPage: 'var(--colors-background-page)',
  backgroundCard: 'var(--colors-background-card)',
  backgroundHighlight: 'linear-gradient(276deg, #00E0FF, #0061FF)',
  backgroundHighlightHover: 'linear-gradient(276deg, #00e0ff 37%, #126bfe)',
  backgroundBanner: 'linear-gradient(270deg, #242993 65%, #254cdd 109%)',
  focus: 'var(--colors-focus)',
  logo: 'var(--colors-logo)',
  chart: 'var(--colors-chart)',
  gradientOverlay: 'var(--colors-gradient-overlay)',
  greyDynamic: 'var(--colors-grey-dynamic)',
  grey: '#798eae',
  lightGrey: '#c9d2df',
  darkGrey: '#364763',
  white: '#ffffff',
  green: '#20d89e',
  red: '#f73f3f',
  gold: '#ffb800',
  lightBlue: '#0061ff',
  textPrimary: 'var(--colors-text-primary)',
  textSecondary: '#798eae',
  textTertiary: 'var(--colors-text-tertiary)',
  textQuaternary: 'var(--colors-text-quaternary)'
}
